### ISSUE TITLE
Is the value providing from .dockerid worth the cost prompting for the Docker ID?

### ISSUE THREAD

**Issue by salcode** [asharirfan/local-wpcli#1]
@asharirfan This is a very cool project.  I'm doing something similar with [salcode/ssh-into-local-by-flywheel](https://github.com/salcode/ssh-into-local-by-flywheel), however wrapping everything in a npm package is a cool idea I'd not considered.

In my experience, the WP CLI portion should work without the `.dockerid` file.  In my project, I include it so I can use my `ssh-lbf` command to SSH directly into the Docker instance.

Since this project focuses on WP CLI, I think you can get away without the `.dockerid` file.

I think this could be a real win because you'll eliminate one of the user prompts (which is always good 😀 ) and in my experience, finding the Docker ID is the most challenging step by far (since the Host IP and Host Port can both be found in the Local by Flywheel dashboard, but Docker ID can not).

Feel free to use the screenshot I already have at https://salferrarello.com/wp-content/uploads/2018/04/local-by-flywheel-database-for-wp-cli.png in your documentation if it is easier than making your own screenshot.

Thanks for sharing this project.

Cheers.

**Comment by asharirfan** [comment]
Hey @salcode  🙌 

> In my experience, the WP CLI portion should work without the .dockerid file. In my project, I include it so I can use my ssh-lbf command to SSH directly into the Docker instance.<br>
> Since this project focuses on WP CLI, I think you can get away without the .dockerid file.

I just checked this, and you're right – works without docker ID. I will include this in the next update ✅ 

Thanks 💯
