### ISSUE TITLE
Remote Host/Port Not Available

### ISSUE THREAD

**Issue by localjo** [asharirfan/local-wpcli#13]
I have a question about how to use this. Local isn't displaying a remote host and port for my site. I want to use the WP-CLI on my local site, which I use for plugin development. I don't have a remote site. Does this package support being used with a local site? 
![Screen Shot 2020-04-24 at 6 40 43 PM](https://user-images.githubusercontent.com/516388/80241504-38b4c500-8653-11ea-8ce1-c76ccf3c5b40.png)

**Comment by asharirfan** [comment]
`local-wpcli` does not currently work with _Local Lightning_. Local by Flywheel has shifted away from container-based environments.

I am looking into possible solutions to make the CLI work with the current version of Local.

**Comment by asharirfan** [comment]
Closing this issue in favor of #17
