### ISSUE TITLE
Support for Local Lightning

### ISSUE THREAD

**Issue by asharirfan** [asharirfan/local-wpcli#17]
## Description

I am opening this issue to keep track of the support for local lightning. I have recently explored how it creates the script files to launch the WP-CLI environment. And how I can integrate it with my cli.

**Comment by joshuaiz** [comment]
Just came looking for this...was using `local-wpcli` before Lightning so a +1 from me.

**Comment by sibelius** [comment]
any updates on this one?

**Comment by t-lock** [comment]
@asharirfan +1 would be great. Local "Lightning" has an issue where their "Open Site Shell" UI doesn't work with ZSH. I recall your initial reason for building local-wpcli was to streamline your workflow. Imagine having to log out and back in to switch terminal to Bash from ZSH just to be able to get WP-CLI on your LocalWP sites :sweat_smile: 

Cheers

**Comment by asharirfan** [comment]
Closing this issue in favour of #20 

I just published v2.0.0 of the CLI and it now support Local Lightning: https://www.npmjs.com/package/local-wpcli
